import './course-page.js';

(function(){
const c=window.COURSE,esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));document.title=`MCP ${c.number} · ${c.title}`;document.querySelector('#source-link').href=c.repo;const prev=document.querySelector('#previous-link'),next=document.querySelector('#next-link');prev.href=c.previous.url;prev.textContent=`← MCP ${c.previous.number}`;next.href=c.next.url;next.textContent=`MCP ${c.next.number} →`;
const lab=(x,i)=>{if(!x)return'';const id=`lab-${i}`;if(x.kind==='flow')return `<section class="lab" id="${id}" data-kind="flow"><div class="lab-head"><span>${esc(x.title)}</span><span>Click a step</span></div><div class="lab-body"><div class="flow-grid">${x.steps.map((s,j)=>`<button class="flow-step${j?'':' active'}" data-i="${j}"><small>0${j+1}</small>${esc(s.name)}</button>`).join('')}</div><div class="output"><h4>${x.steps[0].name}</h4><div>${x.steps[0].detail}</div></div></div></section>`;if(x.kind==='choices')return `<section class="lab" id="${id}" data-kind="choices"><div class="lab-head"><span>${esc(x.title)}</span><span>Try a scenario</span></div><div class="lab-body"><div class="button-row">${x.items.map((s,j)=>`<button class="choice${j?'':' active'}" data-i="${j}">${esc(s.name)}</button>`).join('')}</div><div class="output"><h4>${x.items[0].heading}</h4><div>${x.items[0].detail}</div></div></div></section>`;if(x.kind==='calculator')return `<section class="lab" id="${id}" data-kind="calculator"><div class="lab-head"><span>${esc(x.title)}</span><span>Adjust demand</span></div><div class="lab-body">${x.inputs.map(v=>`<label class="meter"><span>${esc(v.label)}</span><input type="range" min="${v.min}" max="${v.max}" value="${v.value}" step="${v.step||1}" data-key="${v.key}"><output>${v.value}</output></label>`).join('')}<div class="result"><div><small>Requests / day</small><strong data-result="requests">—</strong></div><div><small>Vendor compute</small><strong data-result="cost">—</strong></div><div><small>Recommended lane</small><strong data-result="lane">—</strong></div></div></div></section>`;return''};
const nav=c.chapters.map((x,i)=>`<a href="#ch-${i+1}"><span>${String(i+1).padStart(2,'0')}</span>${esc(x.title)}</a>`).join(''),chapters=c.chapters.map((x,i)=>`<section class="chapter" id="ch-${i+1}"><div class="eyebrow">Chapter ${String(i+1).padStart(2,'0')} / ${esc(x.kicker)}</div><h2>${x.title}</h2><p class="dek">${x.dek}</p><div class="prose">${x.body}</div>${x.callout?`<aside class="callout"><b>${esc(x.callout.label)}</b>${x.callout.text}</aside>`:''}${lab(x.lab,i)}<ul class="takeaways">${x.takeaways.map(t=>`<li>${t}</li>`).join('')}</ul></section>`).join('');
const quiz=`<div class="lab"><div class="lab-head"><span>Four decisions</span><span>Self-check</span></div><div class="lab-body"><form id="quiz-form">${c.quiz.map((x,i)=>`<div class="quiz-q"><p>${i+1}. ${esc(x.q)}</p>${x.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join('')}</div>`).join('')}<button class="choice" type="submit">Check answers</button><div class="quiz-result" aria-live="polite"></div></form></div></div>`;
document.querySelector('#course-root').innerHTML=`<section class="hero"><div class="meta"><div><strong>Document</strong>MCP-${c.number}</div><div><strong>Scope</strong>${esc(c.scope)}</div><div><strong>Protocol</strong>${esc(c.protocol)}</div><div><strong>Read time</strong>${esc(c.readTime)}</div></div><h1>${c.hero}</h1><p class="lead">${c.lead}</p><div class="legend"><span class="host">Host / client</span><span class="server">MCP server</span><span class="wire">Protocol boundary</span><span class="product">Product system</span></div></section><div class="layout"><aside class="rail"><div class="rail-inner"><div class="rail-label">Field notes</div><nav>${nav}</nav></div></aside><main id="lesson">${chapters}<section class="chapter" id="check"><div class="eyebrow">Knowledge check</div><h2>Can you defend the design?</h2><p class="dek">The score matters less than the reasoning behind each answer.</p>${quiz}</section></main></div><footer class="course-footer"><div><small>Continue the sequence</small><strong>${esc(c.next.label)}</strong></div><a href="${c.next.url}">Open MCP ${c.next.number} →</a><a href="${c.repo}">Read the code ↗</a></footer>`;
function bind(el,items){const out=el.querySelector('.output');el.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{el.querySelectorAll('button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const x=items[+btn.dataset.i];out.innerHTML=`<h4>${x.heading||x.name}</h4><div>${x.detail}</div>`})}document.querySelectorAll('[data-kind="flow"]').forEach((el,i)=>bind(el,c.chapters.filter(x=>x.lab?.kind==='flow')[i].lab.steps));document.querySelectorAll('[data-kind="choices"]').forEach((el,i)=>bind(el,c.chapters.filter(x=>x.lab?.kind==='choices')[i].lab.items));document.querySelectorAll('[data-kind="calculator"]').forEach(el=>{const update=()=>{const v={};el.querySelectorAll('input').forEach(x=>{v[x.dataset.key]=+x.value;x.nextElementSibling.textContent=x.value});Object.entries(c.calculator(v)).forEach(([k,val])=>el.querySelector(`[data-result="${k}"]`).textContent=val)};el.oninput=update;update()});
document.querySelector('#quiz-form').onsubmit=e=>{e.preventDefault();let score=0,fd=new FormData(e.currentTarget);c.quiz.forEach((q,i)=>{if(+fd.get(`q${i}`)===q.answer)score++});e.currentTarget.querySelector('.quiz-result').textContent=`${score}/${c.quiz.length}. ${score===c.quiz.length?'You can defend the architecture.':'Revisit the decisions that blur protocol and product behavior.'}`};const links=[...document.querySelectorAll('.rail a')],io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-20% 0px -65%'});document.querySelectorAll('.chapter').forEach(x=>io.observe(x));
})();

// Keep generated teaching panels semantic as their interactive content changes.
(function normalizeGeneratedSemantics(){
  const normalize=()=>{
    document.querySelectorAll('.output h4').forEach(node=>{
      const title=document.createElement('div');
      title.className='output-title';
      title.innerHTML=node.innerHTML;
      node.replaceWith(title);
    });
    document.querySelectorAll('.callout').forEach(node=>node.setAttribute('role','note'));
    const hero=document.querySelector('.hero');
    if(hero){hero.setAttribute('role','region');hero.setAttribute('aria-label','Course introduction')}
  };
  normalize();
  new MutationObserver(normalize).observe(document.querySelector('#course-root'),{childList:true,subtree:true});
})();
