import { lookup } from 'node:dns/promises';
import type { Sql } from './db.js';
import { id } from './db.js';
import type { Actor } from './policy.js';
import { entitlement, Fault } from './policy.js';

type Bucket={tokens:number;at:number};
export class FairLimiter {
  private buckets=new Map<string,Bucket>(); private active=new Map<string,number>();
  constructor(public capacity=10,public refillPerSecond=2,public concurrency=3,private now=()=>Date.now()){}
  enter(a:Actor,cost=1){const key=`${a.org}:${a.id}`,now=this.now(),b=this.buckets.get(key)??{tokens:this.capacity,at:now};b.tokens=Math.min(this.capacity,b.tokens+(now-b.at)/1000*this.refillPerSecond);b.at=now;if(b.tokens<cost)throw new Fault('RATE_LIMITED','Your request allowance is temporarily exhausted. Retry later.',429,true);const active=this.active.get(a.org)??0;if(active>=this.concurrency)throw new Fault('CONCURRENCY_LIMIT','This organization has too many operations in flight.',429,true);b.tokens-=cost;this.buckets.set(key,b);this.active.set(a.org,active+1);let left=false;return()=>{if(!left){left=true;this.active.set(a.org,Math.max(0,(this.active.get(a.org)??1)-1));}};}
}
export class Budget {constructor(public db:Sql){}async reserve(a:Actor,estimate:number){if(!Number.isInteger(estimate)||estimate<1)throw new Fault('INVALID_COST','Estimate must be a positive integer.');const r=await this.db.query(`UPDATE usage SET reserved=reserved+$1 WHERE org=$2 AND spent+reserved+$1<=allowance RETURNING *`,[estimate,a.org]);if(!r.rows.length)throw new Fault('BUDGET_EXCEEDED','The organization budget cannot reserve this work.',429);const reservation=id();await this.db.query('INSERT INTO reservations(id,org,amount) VALUES($1,$2,$3)',[reservation,a.org,estimate]);return reservation;}async reconcile(a:Actor,reservation:string,actual:number){const r=(await this.db.query(`UPDATE reservations SET actual=$1,state='settled' WHERE id=$2 AND org=$3 AND state='reserved' RETURNING amount`,[actual,reservation,a.org])).rows[0];if(!r)throw new Fault('INVALID_RESERVATION','Reservation is missing or already settled.',409);await this.db.query('UPDATE usage SET reserved=reserved-$1,spent=spent+$2 WHERE org=$3',[r.amount,actual,a.org]);}}
function privateAddress(ip:string){return ip==='::1'||ip==='0.0.0.0'||ip.startsWith('127.')||ip.startsWith('10.')||ip.startsWith('192.168.')||ip.startsWith('169.254.')||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:')||/^172\.(1[6-9]|2\d|3[01])\./.test(ip)}
export class SafeImporter {constructor(public maxBytes=256_000,public maxRedirects=3,private resolve=lookup){}async validate(raw:string){const url=new URL(raw);if(url.protocol!=='https:')throw new Fault('URL_REJECTED','Only HTTPS URLs are allowed.');if(url.username||url.password)throw new Fault('URL_REJECTED','Credentials in URLs are not allowed.');const answers=await this.resolve(url.hostname,{all:true});if(!answers.length||answers.some(x=>privateAddress(x.address)))throw new Fault('URL_REJECTED','The URL resolves to a private or local network.');return url;}async fetch(raw:string,signal=AbortSignal.timeout(5000)){let url=await this.validate(raw);for(let n=0;n<=this.maxRedirects;n++){const r=await fetch(url,{redirect:'manual',signal,headers:{Accept:'text/html,text/plain'}});if(r.status>=300&&r.status<400){const next=r.headers.get('location');if(!next||n===this.maxRedirects)throw new Fault('URL_REJECTED','Redirect chain is invalid or too long.');url=await this.validate(new URL(next,url).href);continue;}if(!r.ok)throw new Fault('IMPORT_FAILED',`Remote server returned HTTP ${r.status}.`,502,r.status>=500);const length=Number(r.headers.get('content-length')??0);if(length>this.maxBytes)throw new Fault('TOO_LARGE','Remote content exceeds the import limit.',413);const reader=r.body?.getReader();let size=0,text='';const decoder=new TextDecoder();while(reader){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>this.maxBytes){await reader.cancel();throw new Fault('TOO_LARGE','Remote content exceeds the import limit.',413)}text+=decoder.decode(part.value,{stream:true});}return text.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}throw new Fault('IMPORT_FAILED','Import did not complete.',502);}}
export class Jobs {constructor(public db:Sql){}async create(a:Actor,input:unknown){entitlement(a,'Background jobs');const job=id();await this.db.query(`INSERT INTO jobs(id,actor,org,status,input) VALUES($1,$2,$3,'queued',$4)`,[job,a.id,a.org,JSON.stringify(input)]);return{jobId:job,status:'queued'};}async get(a:Actor,jobId:string){const j=(await this.db.query('SELECT id,status,result,attempts,expires_at FROM jobs WHERE id=$1 AND org=$2 AND actor=$3',[jobId,a.org,a.id])).rows[0];if(!j)throw new Fault('NOT_FOUND','Job not found for this actor.',404);return j;}async lease(_worker:string,seconds=30){return(await this.db.query(`UPDATE jobs SET status='working',lease_until=now()+($1||' seconds')::interval,attempts=attempts+1 WHERE id=(SELECT id FROM jobs WHERE (status='queued' OR (status='working' AND lease_until<now())) AND expires_at>now() ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`,[seconds])).rows[0];}async complete(jobId:string,result:unknown){await this.db.query(`UPDATE jobs SET status='completed',result=$2,lease_until=null WHERE id=$1 AND status='working'`,[jobId,JSON.stringify(result)]);}}
export type Hop={traceId:string;deadline:number;budget:number;visited:string[]};export function nextHop(h:Hop,server:string,cost:number):Hop{if(h.deadline<=Date.now())throw new Fault('DEADLINE','Composite deadline expired.',504);if(h.budget<cost)throw new Fault('BUDGET_EXCEEDED','Composite cost budget exhausted.',429);if(h.visited.includes(server))throw new Fault('RECURSION','Composite server cycle detected.',508);if(h.visited.length>=5)throw new Fault('HOP_LIMIT','Composite call depth exceeded.',508);return{...h,budget:h.budget-cost,visited:[...h.visited,server]};}
export class ProductionControls {limiter=new FairLimiter();budget:Budget;jobs:Jobs;importer=new SafeImporter();constructor(db:Sql){this.budget=new Budget(db);this.jobs=new Jobs(db)}}
